# 16 Jan 2026

In [6]:
!pip3 install numpy

In [7]:
import numpy as np
v = np.array([1,2,3,4,5])
type(v)

numpy.ndarray

In [3]:
v = np.ones(10)
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
v = np.zeros(4)
v

array([0., 0., 0., 0.])

In [5]:
v1 = np.array([1,2,3,4,10])
v2 = np.array([4,3,2,1,6])
v1+v2

array([ 5,  5,  5,  5, 16])

In [8]:
v1-v2

array([-3, -1,  1,  3,  4])

In [9]:
v1*v2

array([ 4,  6,  6,  4, 60])

In [10]:
v1/v2

array([0.25      , 0.66666667, 1.5       , 4.        , 1.66666667])

In [11]:
v1%v2

array([1, 2, 1, 0, 4])

In [ ]:
v1 = np.array([1,2,3,4,10])
v2 = np.array([4,3,2,1,6])

In [12]:
30%5

0

In [13]:
v1**v2

array([      1,       8,       9,       4, 1000000])

In [ ]:
1*1*1*1==1
2*2*2

In [14]:
v1 = np.array([1,2,3,4,10])
v2 = np.array([4,3,2,1,6])
v1.dot(v2)

80

In [15]:
1*4+2*3+3*2+4*1+10*6

80

In [17]:
import numpy as np
m = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
import numpy as np
m = np.ones((5,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
m = np.zeros((2,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
m = np.random.rand(4)
m

array([0.7360705 , 0.20381794, 0.69075557, 0.54954046])

In [22]:
m = np.random.rand(3,4)
m

array([[0.46739854, 0.47847361, 0.20563869, 0.3537835 ],
       [0.05469488, 0.54641707, 0.70169096, 0.22955071],
       [0.97622707, 0.20515307, 0.42818681, 0.34091918]])

In [23]:
m.shape

(3, 4)

In [24]:
m.ndim

2

In [25]:
v.ndim

1

In [26]:
data = np.array(4)
data.ndim

0

In [28]:
import numpy as np
I = np.eye(N=3,M=4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [30]:
import numpy as np
m1 = np.array([
    [4,2],
    [1,3]
])
m2 = np.array(
    [
        [1,2],
    [2,1]
    ]
)

m2@m1


array([[6, 8],
       [9, 7]])

In [31]:
m1*m2

array([[4, 4],
       [2, 3]])

In [32]:
import numpy as np
m1 = np.array([
    [4,2],
    [1,3]
])
v = np.array(
    [1,2]
)
m1@v

array([8, 7])

In [34]:
import numpy as np

m = np.random.rand(3,2)
print(m)
print(m.T)

[[0.02601353 0.09743212]
 [0.31847233 0.94809149]
 [0.47719029 0.8909983 ]]
[[0.02601353 0.31847233 0.47719029]
 [0.09743212 0.94809149 0.8909983 ]]


In [37]:
import numpy as np
m = np.array([
    [2,3],
    [1,2]
])
det = np.linalg.det(m)
if det!=0:
    inv = np.linalg.inv(m)
    print(inv)
else:
    print("Inverse does not exist")
m@inv

[[ 2. -3.]
 [-1.  2.]]


array([[1., 0.],
       [0., 1.]])

In [39]:
import numpy as np
import pandas as pd
i = np.array([1,2])
j = np.array([3,4])

result = np.column_stack((i,j))
result

array([[1, 3],
       [2, 4]])

In [40]:
import numpy as np
m1 = np.array([
    [2,4,5],
    [5,4,6],
    [4,5,3]
])
m2 = np.array([
    [1,4,2],
    [3,4,2],
    [6,4,1]
])
m1@m2

array([[44, 44, 17],
       [53, 60, 24],
       [37, 48, 21]])

In [41]:
m2@m1

array([[30, 30, 35],
       [34, 38, 45],
       [36, 45, 57]])

In [43]:
m1@np.eye(N=3,M=3)

array([[2., 4., 5.],
       [5., 4., 6.],
       [4., 5., 3.]])