# 16 Jan 2026

In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
v = np.array([1,2,3,4,5])
type(v)

numpy.ndarray

In [6]:
v =  np.ones(10)
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
v = np.zeros(2)
v

array([0., 0.])

In [9]:
vector1 = np.array([10, 12, 14])
vector2 = np.array([2, 4, 6])

vector1 + vector2

array([12, 16, 20])

In [10]:
vector1 - vector2

array([8, 8, 8])

In [11]:
vector1 * vector2

array([20, 48, 84])

In [12]:
vector1 / vector2

array([5.        , 3.        , 2.33333333])

In [ ]:
vector1 % vector2 # Remainder

array([0, 0, 2])

In [ ]:
vector1 ** vector2 # power 10^2 (10 * 10)

array([    100,   20736, 7529536])

In [17]:
v1=np.array([1,2,3,4,10]) #1*4+2*4+
v2=np.array([4,4,2,1,6])

print(v1.dot(v2))

82


In [19]:
m = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
m = np.ones([3,5])

m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
m = np.zeros([5,7])
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [23]:
v = np.random.rand(5)
v

array([0.70292025, 0.14540305, 0.22670407, 0.88286097, 0.26280268])

In [25]:
m = np.random.rand(4,5)
m

array([[0.95019661, 0.07834903, 0.69905752, 0.66028706, 0.45167928],
       [0.93640782, 0.73829717, 0.88190454, 0.11047846, 0.78945922],
       [0.97741594, 0.67129166, 0.86149988, 0.8539328 , 0.03468127],
       [0.02926143, 0.44766104, 0.41503028, 0.88740284, 0.217663  ]])

In [26]:
m.shape

(4, 5)

In [27]:
v.shape

(5,)

In [ ]:
v.ndim #vector

1

In [ ]:
data=np.array(1) #scalar
data.ndim

0

In [33]:
import numpy as np

m1 = np.array([
    [4,2],
    [1,3]
])
m2 = np.array([
    [1,2],
    [2,1]
])

m1@m2

array([[ 8, 10],
       [ 7,  5]])

In [31]:
m2@m1

array([[6, 8],
       [9, 7]])

In [34]:
m1 = np.array([
    [4,2],
    [1,3]
])
v = np.array(
    [1,2])

m1@v

array([8, 7])

In [37]:
import numpy as np

m = np.random.rand(3,2)
print(m)
print(m.T)

[[0.4342832  0.43753918]
 [0.66850669 0.30934957]
 [0.27232255 0.27363272]]
[[0.4342832  0.66850669 0.27232255]
 [0.43753918 0.30934957 0.27363272]]


In [38]:
import numpy as np

m = np.array([
    [2,3],
    [1,2]
])

det = np.linalg.det(m)

if det!=0:
    inv=np.linalg.inv(m)
    print(inv)
else:
    print("Inverse does not exist")

m@inv

[[ 2. -3.]
 [-1.  2.]]


array([[1., 0.],
       [0., 1.]])

In [ ]:
import numpy as np 
import pandas as p
#strech matrix or stacking of multiple matrix

i = np.array([1,2])
j = np.array([3,4])

result = np.column_stack((i,j))
result

array([[1, 3],
       [2, 4]])

In [ ]:
import numpy as np
import pandas as pd

i = np.array([1,2])
j = np.array([3,4])

data = pd.DataFrame()
data['i']= i
data['j']= j
data


i  j
0  1  3
1  2  4

In [13]:
import numpy as np

m = np.array([
    [2,4,5],
    [4,7,9],
    [2,6,8]
])

v = np.array([2,3,6])

print("Matrix:")
print(m)
print(f"Vector : {v}")

print("Matrix multiplication :")
print(m@v)

print("Transpose of matrix :" )
print(m.T)


Matrix:
[[2 4 5]
 [4 7 9]
 [2 6 8]]
Vector : [2 3 6]
Matrix multiplication :
[46 83 70]
Transpose of matrix :
[[2 4 2]
 [4 7 6]
 [5 9 8]]


In [14]:
print("Determinant of matrix :")
det = np.linalg.det(m)
print(det)

if det!=0:
    print("Inverse of the matrix :")
    inv = np.linalg.inv(m)
    print(inv)
else:
    print("Determinant is zero.. so inverse cannot be performed")


Determinant of matrix :
-2.000000000000002
Inverse of the matrix :
[[-1.   1.  -0.5]
 [ 7.  -3.  -1. ]
 [-5.   2.   1. ]]


In [6]:
import numpy as np

m = np.array([
    [2,4,5],
    [4,7,9],
    [2,6,8]
])

print("Determinant of matrix :")
det = np.linalg.det(m)
print(det)

if det!=0:
    print("Inverse of the matrix :")
    inv = np.linalg.inv(m)
    print(inv)
else:
    print("Determinant is zero.. so inverse cannot be performed")


print("Compute matrix & inverse matrix :")
m@inv

Determinant of matrix :
-2.000000000000002
Inverse of the matrix :
[[-1.   1.  -0.5]
 [ 7.  -3.  -1. ]
 [-5.   2.   1. ]]
Compute matrix & inverse matrix :


array([[ 1.00000000e+00,  0.00000000e+00, -8.88178420e-16],
       [-2.66453526e-15,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [8]:
m = np.array([
    [2,4,5],
    [4,7,9],
    [2,6,8]
])

inv = np.array([
    [-1,1,-0.5],
    [7,-3,-1],
    [-5,2,1]
])

print("Compute matrix & inverse matrix :")
m@inv

Compute matrix & inverse matrix :


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
print(f"Matrix : {m}")
print(f"Vector : {v}")

print("Strech matrix : ")
print(np.column_stack((m,v)))

Matrix : [[2 4 5]
 [4 7 9]
 [2 6 8]]
Vector : [2 3 6]
Strech matrix : 
[[2 4 5 2]
 [4 7 9 3]
 [2 6 8 6]]


In [24]:
v1 = np.array([[1,2,3],
               [2,5,7]])
v2 = np.array([4,3,2])
print(v1.dot(v2))


[16 37]


In [28]:
import numpy as np
import pandas as pd

st=np.column_stack((m,v))
print(st)
data=pd.DataFrame(st)
data

[[2 4 5 2]
 [4 7 9 3]
 [2 6 8 6]]


0  1  2  3
0  2  4  5  2
1  4  7  9  3
2  2  6  8  6