## 18-01-2016


## Use numpy create a 3x3 matrix A and a Vector V - hardcoded values

In [5]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

v = np.array([3,6,9])

print(f"Matrix: {a}")
print(f"Vector: {v}")

Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector: [3 6 9]


## To compute A.V - Matrix multiplication

In [6]:
a@v

array([ 42,  96, 150])

In [ ]:
#Manual calcuation

1*3+2*6+3*9 = 42
4*3+5*6+6*9 = 96
7*3+8*6+9*9 = 150

# Transpose of Matrix A

In [8]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Transpose - change in row to column & column to row

# Compute determinant of A

In [2]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

det = np.linalg.det(a)
print(det)

if det!=0:
    inv=np.linalg.inv(a)
    print(inv)
else:
    print("Determinant is zero.. so inverse cannot be performed")

0.0
Determinant is zero.. so inverse cannot be performed


In [ ]:
# determinant for 3x3 matrix 
# det(a) = 1((5*9)-(6*8)) - 2((4*9)-(6*7)) + 3((4*8)-(5*7)) 
#        = -3 + 12 - 9
#        = 0 

# As the determinant of matrix "a" is 0 , we will not be able to find inverse of this matrix

## Use numpy create a 3x3 matrix A and a Vector V - random values

In [25]:
import numpy as np

mat = np.random.rand(3,3)
vec = np.random.rand(3)

print("Matrix:")
print(mat)
print(f"Vector : {vec}")

print("Matrix multiplication :")
print(mat@vec)

print("Transpose of matrix :" )
print(mat.T)

print("Determinant of matrix :")
det = np.linalg.det(mat)
print(det)

if det!=0:
    inv = np.linalg.inv(mat)
    print("Inverse of matrix :")
    print(inv)

Matrix:
[[0.55572799 0.01833101 0.49288761]
 [0.86962076 0.74931017 0.02861009]
 [0.43596346 0.29692698 0.47923429]]
Vector : [0.09692274 0.09728147 0.85046979]
Matrix multiplication :
[0.47483197 0.18151203 0.47871455]
Transpose of matrix :
[[0.55572799 0.86962076 0.43596346]
 [0.01833101 0.74931017 0.29692698]
 [0.49288761 0.02861009 0.47923429]]
Determinant of matrix :
0.1536853110426797
Inverse of matrix :
[[ 2.28128517  0.89511993 -2.39971697]
 [-2.63056458  0.33472897  2.68552582]
 [-0.44544258 -1.02169157  2.60578977]]


In [ ]:
# Matrix with identity matrix 

mat@np.eye(N=3,M=3)

array([[0.55572799, 0.01833101, 0.49288761],
       [0.86962076, 0.74931017, 0.02861009],
       [0.43596346, 0.29692698, 0.47923429]])

In [ ]:
mat@inv 

array([[ 1.00000000e+00, -3.10466788e-18,  1.47843963e-17],
       [ 1.48226414e-16,  1.00000000e+00, -4.76132798e-16],
       [-2.29740004e-17, -4.47430902e-17,  1.00000000e+00]])